#!/bin/bash

PWDx=$PWD

mkdir /opt
cd /opt

rm -rf setVer*
rm -rf version*
rm -rf studio*

wget https://developer.android.com/studio#downloads

cat studio | grep -o -P '(?<=https://redirector.gvt1.com/edgedl/android/studio/ide-zips/).*(?=-linux.tar.gz)' > setVer
rm -rf studio*

cat setVer | grep -o -P '(?<=).*(?=/android-studio)' > version
rm -rf setVer*

version=$(head -n 1 version)
rm -rf version

rm -rf android-studio-$version-linux.tar.gz*
wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/$version/android-studio-$version-linux.tar.gz
sudo tar zxvf android-studio-*

while true; do
        dialog \
                --title "Open Android Studio" \
                --clear \
                --yesno "" 0 0

        case $? in
                0 )
                        bash /opt/android-studio/bin/studio.sh

                break
                ;;
                1 )
                				clear
                        exit 1
                break
                ;;
                255 )
                        clear
                        exit 1
                break
                ;;
        esac
done

cd PWDx
